### ISSUE TITLE
Add case insensitive RankFind

### ISSUE THREAD

**Issue by ktprograms** [lithammer/fuzzysearch#31]
Hi, thanks for this library!

Currently, it seems that MatchFold can be used for case insensitive matching, but there doesn't seem to be any way to do case insensitive RankFind.

**Comment by ktprograms** [comment]
So sorry, I didn't look at the code. I just saw that there _are_ `*Fold` versions of most functions.

I'll make a PR to update the README for how to use case insensitive matching soon.

**Comment by eloo** [comment]
@lithammer just want to catch up this issue for a question..
is the rankfind really case insensitive with fold? 

```
{BEER beer 4 5}
```

because it seems that the rankfindfold with find the value but the distance is not 0 here.. its 4. 
so i'm curious if this is expected or not.. because if want to get a really case insensitive result here i would also expect to get a distance of 0 here.

what do you think?
